<a href="https://colab.research.google.com/github/fahim1703061/colab_2022/blob/main/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 3.2: Numpy in Python

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.arange(1, 9, 2)

print(arr)

[1 3 5 7]


In [ ]:
#n array with zero float values

arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [ ]:
#n array with zero int values

arr = np.zeros(4, int)
arr

array([0, 0, 0, 0])

In [ ]:
#n*m array with zero float values

arr = np.zeros([4,3])
print(arr)
arr

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#n*m identity matrix with zero float values

arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#n*n diagonal matrix with zero float values

arr = np.diag([5,2,6,9])
arr

array([[5, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

## Random Generation in Numpy

In [ ]:
rnd_arr = np.random.rand(5)
rnd_arr

array([0.18413099, 0.7198719 , 0.82931773, 0.48212295, 0.60902322])

In [ ]:
rand_int = np.random.randint(1, 10, 10)
rand_int

array([1, 9, 3, 6, 5, 3, 8, 6, 9, 4])

In [ ]:
n = rand_int.max()
n

9

In [ ]:
rand_int[5]

3

In [ ]:
rand_int[2:6]

array([3, 6, 5, 3])

In [ ]:
rand_int[:7]  #slicing

array([1, 9, 3, 6, 5, 3, 8])

In [ ]:

arr2d = np.random.randint(1, 100, (4,4))
arr2d

array([[30, 88,  1, 89],
       [27, 68, 46, 25],
       [41, 89, 56, 43],
       [32, 52, 16, 14]])

In [ ]:
arr2d[2]

array([41, 89, 56, 43])

In [7]:
#making 1d array to n*m -array

arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
#making 1d array to n*m -array

arr = np.arange(12).reshape(3,4) #error will occur  for shape (4,4). n*m should be equal to 12
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
arr[1][2]

6

In [6]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
print(arr[0:2, 1:4])

[[1 2 3]
 [5 6 7]]


In [13]:
#arithmetic operation on array

arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
print(arr+arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [16]:
arrAddend = np.arange(1, 13)

print(arr + arrAddend)         #two array length must be same

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [22]:
# 2D array creation

arr = np.array([
    [1,2,3],
    [4,5,6]
    
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
print(arr.dtype)

int64


In [24]:
print(arr.ndim)

2


In [26]:
print(arr.size)    #total element

6


<h1><b>Five number summary

In [ ]:
import numpy as np

def fivenum(data):
    """Five-number summary."""
    return np.percentile(data, [0, 25, 50, 75, 100], interpolation='midpoint')

In [ ]:
moons = [0, 0, 1, 2, 63, 61, 27, 13,300]
print(fivenum(moons))

[  0.   1.  13.  61. 300.]
