<a href="https://colab.research.google.com/github/fahim1703061/colab_2022/blob/main/python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 3.2: Numpy in Python

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.arange(1, 9, 2)

print(arr)

[1 3 5 7]


In [4]:
#n array with zero float values

arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [10]:
#n array with zero int values

arr = np.zeros(4, int)
arr

array([0, 0, 0, 0])

In [9]:
#n*m array with zero float values

arr = np.zeros([4,3])
print(arr)
arr

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#n*m identity matrix with zero float values

arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#n*n diagonal matrix with zero float values

arr = np.diag([5,2,6,9])
arr

array([[5, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 9]])

## Random Generation in Numpy